id: gcp_bucket_scheduled
namespace: blockchain

inputs:
  - id: data_type
    type: SELECT
    displayName: Select data type
    values: [blocks, transactions]
    defaults: blocks

variables:
  file: "{{inputs.data_type}}/{{trigger.date | date('yyyy')}}/{{trigger.date | date('MM')}}/btc_{{trigger.date | date('yyyyMM')}}-*.parquet"
  gcs_file: "gs://{{kv('GCP_BUCKET_NAME')}}/{{vars.file}}"

tasks:
  - id: set_label
    type: io.kestra.plugin.core.execution.Labels
    labels:
      file: "{{render(vars.file)}}"
      data_type: "{{inputs.data_type}}"

  - id: if_blocks_data
    type: io.kestra.plugin.core.flow.If
    condition: "{{inputs.data_type == 'blocks'}}"
    then:
      - id: bq_query_blocks
        type: io.kestra.plugin.gcp.bigquery.Query
        projectId: "{{kv('GCP_PROJECT_ID')}}"
        destinationTable: "{{kv('GCP_DATASET_TEMP')}}.btc_{{inputs.data_type}}_temp_{{trigger.date | date('yyyyMM')}}"
        sql: |
          SELECT *
          FROM `bigquery-public-data.crypto_bitcoin.blocks`
          WHERE DATE(timestamp_month) = '{{trigger.date | date('yyyy-MM')}}-01'
        writeDisposition: WRITE_TRUNCATE

      - id: extract_to_gcs_blocks
        type: io.kestra.plugin.gcp.bigquery.ExtractToGcs
        destinationUris:
          - "{{render(vars.gcs_file)}}"
        sourceTable: "{{kv('GCP_PROJECT_ID')}}.{{kv('GCP_DATASET_TEMP')}}.btc_{{inputs.data_type}}_temp_{{trigger.date | date('yyyyMM')}}"
        format: PARQUET

  - id: if_transactions_data
    type: io.kestra.plugin.core.flow.If
    condition: "{{inputs.data_type == 'transactions'}}"
    then:
      - id: bq_query_transactions
        type: io.kestra.plugin.gcp.bigquery.Query
        projectId: "{{kv('GCP_PROJECT_ID')}}"
        destinationTable: "{{kv('GCP_DATASET_TEMP')}}.btc_{{inputs.data_type}}_temp_{{trigger.date | date('yyyyMM')}}"
        sql: |
          SELECT *
          FROM `bigquery-public-data.crypto_bitcoin.transactions`
          WHERE DATE(block_timestamp_month) = '{{trigger.date | date('yyyy-MM')}}-01'
        writeDisposition: WRITE_TRUNCATE

      - id: extract_to_gcs_transactions
        type: io.kestra.plugin.gcp.bigquery.ExtractToGcs
        destinationUris:
          - "{{render(vars.gcs_file)}}"
        sourceTable: "{{kv('GCP_PROJECT_ID')}}.{{kv('GCP_DATASET_TEMP')}}.btc_{{inputs.data_type}}_temp_{{trigger.date | date('yyyyMM')}}"
        format: PARQUET

  - id: purge_files
    type: io.kestra.plugin.core.storage.PurgeCurrentExecutionFiles
    description: If you'd like to explore Kestra outputs, disable it.
    disabled: false

pluginDefaults:
  - type: io.kestra.plugin.gcp
    values:
      serviceAccount: "{{kv('GCP_CREDS')}}"
      projectId: "{{kv('GCP_PROJECT_ID')}}"
      location: "{{kv('GCP_LOCATION')}}"
      bucket: "{{kv('GCP_BUCKET_NAME')}}"

triggers:
  - id: blocks_schedule
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "0 12 1 * *"
    inputs:
      data_type: blocks

  - id: transactions_schedule
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "0 13 1 * *"
    inputs:
      data_type: transactions
